# This file was generated by GoReleaser. DO NOT EDIT.
cask "dnscontrol" do
  desc "DNSControl: Infrastructure as Code for DNS Zones"
  homepage "https://docs.dnscontrol.org/"
  version "4.20.1"
  license "MIT"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dnscontrol"

  on_macos do
    url "https://github.com/DNSControl/dnscontrol/releases/download/v4.20.1/dnscontrol_4.20.1_darwin_all.tar.gz"
    sha256 "bf4e6b4382814bc2d04ab2e6b36174f945c4142270176657d12993e32dcd57ab"
  end

  on_linux do
    on_intel do
      url "https://github.com/DNSControl/dnscontrol/releases/download/v4.20.1/dnscontrol_4.20.1_linux_amd64.tar.gz"
      sha256 "bdf938dd8ca84050ef30688bc43aed68f425d6f3421e7443b12f5fdb1aa157a6"
    end
    on_arm do
      url "https://github.com/DNSControl/dnscontrol/releases/download/v4.20.1/dnscontrol_4.20.1_linux_arm64.tar.gz"
      sha256 "c0c10676975256b3fe1b05bfca99855384e9c69bce29412b78a2ea5be04c4f1c"
    end
  end

  conflicts_with formula: "dnscontrol"

  # No zap stanza required
end
