# This file was generated by GoReleaser. DO NOT EDIT.
cask "dnscontrol" do
  version "5.1.0"

  on_macos do
    sha256 "aa725621860bfed80cefc748913f6db37e84937db1e083c79b730b20824bf831"
    url "https://github.com/DNSControl/dnscontrol/releases/download/v#{version}/dnscontrol_#{version}_darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "ce895f7d9352a8fbcad0d46ae6533d2ba3d2a4bcd182f5d52b18fded4dbdb9bc"
      url "https://github.com/DNSControl/dnscontrol/releases/download/v#{version}/dnscontrol_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9f9725ab750d39577b3f33a94a7ff20ba0d7228fb07544627f3210266ec119be"
      url "https://github.com/DNSControl/dnscontrol/releases/download/v#{version}/dnscontrol_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dnscontrol"
  desc "DNSControl: Infrastructure as Code for DNS Zones"
  homepage "https://docs.dnscontrol.org/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dnscontrol"

  # No zap stanza required
end
