# This file was generated by GoReleaser. DO NOT EDIT.
cask "dnscontrol" do
  version "4.43.3"

  on_macos do
    sha256 "9faa8877e150747798347736715396e4438cac948a1c984a305d8ab53801b992"
    url "https://github.com/DNSControl/dnscontrol/releases/download/v#{version}/dnscontrol_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "6ccc4a57a341398e09fa95695805eb7133ce7c14140debeef9c0a6cf642a50d1"
      url "https://github.com/DNSControl/dnscontrol/releases/download/v#{version}/dnscontrol_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "59fbe4a3d87faa8cc683aa99df6f72b9714716f3c9a994214f4cfd0ca89308dc"
      url "https://github.com/DNSControl/dnscontrol/releases/download/v#{version}/dnscontrol_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dnscontrol"
  desc "DNSControl: Infrastructure as Code for DNS Zones"
  homepage "https://docs.dnscontrol.org/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dnscontrol"

  # No zap stanza required

end
