# This file was generated by GoReleaser. DO NOT EDIT.
cask "dnscontrol" do
  desc "DNSControl: Infrastructure as Code for DNS Zones"
  homepage "https://docs.dnscontrol.org/"
  version "4.20.1"
  license "MIT"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dnscontrol"

  on_macos do
    url "https://github.com/DNSControl/dnscontrol/releases/download/v4.20.1/dnscontrol_4.20.1_darwin_all.tar.gz"
    sha256 "39bed97a1183934c4e5bb1706ff4e2b954bdf83437cd1bf7e4db23904134f30e"
  end

  on_linux do
    on_intel do
      url "https://github.com/DNSControl/dnscontrol/releases/download/v4.20.1/dnscontrol_4.20.1_linux_amd64.tar.gz"
      sha256 "ae7c66c4f3424329415863f136dee727e21a84e9c05c00fbc7a2af07fe027089"
    end
    on_arm do
      url "https://github.com/DNSControl/dnscontrol/releases/download/v4.20.1/dnscontrol_4.20.1_linux_arm64.tar.gz"
      sha256 "1516b5071b9e4ceb4bea2875617610ad43b6382ca39256e71508821b63b943db"
    end
  end

  conflicts_with formula: "dnscontrol"

  # No zap stanza required
end
